spring.application.name=educore
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
# PostgreSQL Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/educore
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarları (Tabloları otomatik oluşturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Spring Batch Ayarları (Tabloları otomatik oluşturur ve başlangıçta gereksiz çalışmayı önler)
spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false