-- Authentication state: rotating refresh tokens, login attempts (throttling and lockout) and the
-- security audit trail.

-- Opaque refresh tokens. Only the SHA-256 hex digest of the token is stored. Every rotation creates a new
-- row in the same family and marks the presented row revoked with replaced_by pointing at its successor;
-- presenting a revoked token revokes the whole family.
CREATE TABLE refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL,
    token_hash varchar(64) NOT NULL,
    family_id uuid NOT NULL,
    issued_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    replaced_by bigint,
    user_agent varchar(512),
    ip varchar(45),
    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT uk_refresh_token_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_account FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_token_replaced_by FOREIGN KEY (replaced_by) REFERENCES refresh_token (id) ON DELETE SET NULL
);

CREATE INDEX ix_refresh_token_account ON refresh_token (account_id);
CREATE INDEX ix_refresh_token_family ON refresh_token (family_id);

-- Login attempts. The username is never stored: username_hash is HMAC-SHA-256 (hex) keyed with the
-- server-side pepper EDUCORE_LOGIN_PEPPER. Account lockout is derived from the most recent rows per hash,
-- so it applies equally to existing and unknown usernames.
CREATE TABLE login_attempt (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username_hash varchar(64) NOT NULL,
    ip varchar(45) NOT NULL,
    success boolean NOT NULL,
    at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_login_attempt PRIMARY KEY (id)
);

CREATE INDEX ix_login_attempt_username_hash_at ON login_attempt (username_hash, at DESC);

-- Security audit trail. Account ids are kept without foreign keys so that events outlive the accounts
-- they describe.
CREATE TABLE security_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    type varchar(64) NOT NULL,
    actor_account_id bigint,
    target_account_id bigint,
    ip varchar(45),
    request_id varchar(64),
    at timestamp(6) with time zone NOT NULL,
    details jsonb,
    CONSTRAINT pk_security_event PRIMARY KEY (id)
);

CREATE INDEX ix_security_event_type_at ON security_event (type, at);
CREATE INDEX ix_security_event_target ON security_event (target_account_id);
