-- P5 / D-09: IP access control.
--
-- 1. The student IP allow-list keeps its rows under its real name: ip_block -> ip_allocation_range
--    (entity IpAllocationRange). It never blocked requests; it only limits the addresses an ADMIN may assign
--    to an account.
ALTER TABLE ip_block RENAME TO ip_allocation_range;

-- Databases created by Flyway name the key pk_ip_block; databases adopted from Hibernate ddl-auto
-- (baseline-on-migrate) may carry a generated name, which is left as it is.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pk_ip_block') THEN
        ALTER TABLE ip_allocation_range RENAME CONSTRAINT pk_ip_block TO pk_ip_allocation_range;
    END IF;
END
$$;

-- 2. Request-level deny rules, checked by IpAccessControlFilter for every application request.
--    start_ip/end_ip are the inclusive unsigned 32-bit bounds computed by the server from value.
--    expires_at NULL = permanent; source AUTO = written after repeated failed logins from one IP.
--    created_by is an account id without a foreign key, so a rule outlives the ADMIN who created it.
CREATE TABLE ip_deny_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    kind varchar(10) NOT NULL,
    value varchar(31) NOT NULL,
    start_ip bigint NOT NULL,
    end_ip bigint NOT NULL,
    reason varchar(200),
    source varchar(10) NOT NULL,
    expires_at timestamp(6) with time zone,
    created_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_ip_deny_rule PRIMARY KEY (id),
    CONSTRAINT ck_ip_deny_rule_kind CHECK (kind IN ('STATIC', 'RANGE', 'CIDR')),
    CONSTRAINT ck_ip_deny_rule_source CHECK (source IN ('MANUAL', 'AUTO')),
    CONSTRAINT ck_ip_deny_rule_bounds CHECK (start_ip >= 0 AND start_ip <= end_ip AND end_ip <= 4294967295)
);

CREATE INDEX ix_ip_deny_rule_expires_at ON ip_deny_rule (expires_at);
