CREATE TABLE account (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    student_number varchar(255),
    -- EnumType.STRING uses varchar with Hibernate's enum-value check constraint.
    role varchar(255),
    ip_address varchar(255),
    deleted int DEFAULT 0 NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT uk_account_username UNIQUE (username),
    CONSTRAINT uk_account_student_number UNIQUE (student_number),
    CONSTRAINT uk_account_ip_address UNIQUE (ip_address),
    CONSTRAINT ck_account_role CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE course (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    term varchar(255),
    instructor varchar(255),
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uk_course_name UNIQUE (name)
);

CREATE TABLE enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL,
    course_id bigint NOT NULL,
    enrollment_date timestamp(6) without time zone,
    CONSTRAINT pk_enrollments PRIMARY KEY (id),
    CONSTRAINT uk_enrollments_account_course UNIQUE (account_id, course_id),
    CONSTRAINT fk_enrollments_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id) REFERENCES course (id)
);

CREATE TABLE ip_block (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    type varchar(255),
    original_value varchar(255),
    start_ip bigint,
    end_ip bigint,
    CONSTRAINT pk_ip_block PRIMARY KEY (id)
);

CREATE TABLE job_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    file_name varchar(255),
    successful_records integer NOT NULL,
    failed_records integer NOT NULL,
    status varchar(255),
    created_at timestamp(6) without time zone,
    -- Explicit columnDefinition = TEXT; this field is not an @Lob/oid mapping.
    detailed_logs text,
    entity_type varchar(255),
    CONSTRAINT pk_job_log PRIMARY KEY (id)
);

-- PostgreSQL creates the requested indexes for username, student_number and
-- enrollments(account_id, course_id) through their UNIQUE constraints above.
