-- P6 ingestion pipeline: file-level idempotency, structured job logs with row-level entries, and the
-- persistent accept-once state of the inbox poller.

-- One row per accepted CSV file, keyed by the SHA-256 of its bytes. A second file with the same content is
-- rejected as DUPLICATE unless the earlier import FAILED (then the row is reused for the new attempt).
CREATE TABLE imported_file (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    sha256 varchar(64) NOT NULL,
    original_name varchar(255) NOT NULL,
    kind varchar(16) NOT NULL,
    size bigint NOT NULL,
    rows integer NOT NULL,
    status varchar(16) NOT NULL,
    job_execution_id bigint,
    received_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_imported_file PRIMARY KEY (id),
    CONSTRAINT uk_imported_file_sha256 UNIQUE (sha256),
    CONSTRAINT ck_imported_file_kind CHECK (kind IN ('STUDENTS', 'COURSES')),
    CONSTRAINT ck_imported_file_status CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'PARTIAL', 'FAILED'))
);

-- job_log: link to the imported file, run timestamps, read count and the SUCCEEDED/PARTIAL/FAILED outcome.
-- successful_records = rows written, failed_records = rows skipped. status is NULL while the job runs.
ALTER TABLE job_log ADD COLUMN imported_file_id bigint;
ALTER TABLE job_log ADD COLUMN started_at timestamp(6) with time zone;
ALTER TABLE job_log ADD COLUMN finished_at timestamp(6) with time zone;
ALTER TABLE job_log ADD COLUMN read_records integer DEFAULT 0 NOT NULL;
ALTER TABLE job_log ADD COLUMN reason varchar(64);
ALTER TABLE job_log ADD CONSTRAINT fk_job_log_imported_file
    FOREIGN KEY (imported_file_id) REFERENCES imported_file (id) ON DELETE SET NULL;

UPDATE job_log SET status = 'SUCCEEDED' WHERE status = 'SUCCESS';
UPDATE job_log SET status = 'FAILED' WHERE status IS NULL OR status NOT IN ('SUCCEEDED', 'PARTIAL', 'FAILED');
UPDATE job_log SET started_at = created_at, finished_at = created_at WHERE created_at IS NOT NULL;
UPDATE job_log SET read_records = successful_records + failed_records;
ALTER TABLE job_log ALTER COLUMN status TYPE varchar(16);
ALTER TABLE job_log ADD CONSTRAINT ck_job_log_status CHECK (status IN ('SUCCEEDED', 'PARTIAL', 'FAILED'));

CREATE INDEX ix_job_log_created_at ON job_log (created_at DESC, id DESC);
CREATE INDEX ix_job_log_status ON job_log (status);

-- Row-level outcome of a job. raw_masked is the CSV line with every letter and digit after the first of
-- each word replaced by '*'; reason is a fixed code, never an exception message.
CREATE TABLE job_log_entry (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_log_id bigint NOT NULL,
    row_number integer,
    level varchar(8) NOT NULL,
    reason varchar(64) NOT NULL,
    raw_masked varchar(2000),
    CONSTRAINT pk_job_log_entry PRIMARY KEY (id),
    CONSTRAINT fk_job_log_entry_job_log FOREIGN KEY (job_log_id) REFERENCES job_log (id) ON DELETE CASCADE,
    CONSTRAINT ck_job_log_entry_level CHECK (level IN ('INFO', 'WARN', 'ERROR'))
);

CREATE INDEX ix_job_log_entry_job_log ON job_log_entry (job_log_id, row_number);

-- The free-text/JSON detail column is replaced by job_log_entry. Legacy details become one entry per log,
-- masked the same way (they contained student names and numbers).
INSERT INTO job_log_entry (job_log_id, row_number, level, reason, raw_masked)
SELECT id, NULL, 'INFO', 'LEGACY_DETAILS',
       left(regexp_replace(detailed_logs, '([[:alnum:]])[[:alnum:]]+',
                           '\1***', 'g'), 2000)
FROM job_log
WHERE detailed_logs IS NOT NULL AND detailed_logs <> '';

ALTER TABLE job_log DROP COLUMN detailed_logs;

-- Spring Integration JdbcMetadataStore (official PostgreSQL definition, table prefix INT_): keeps the
-- FileSystemPersistentAcceptOnceFileListFilter state of the inbox across restarts.
CREATE TABLE INT_METADATA_STORE (
    METADATA_KEY VARCHAR(255) NOT NULL,
    METADATA_VALUE VARCHAR(4000),
    REGION VARCHAR(100) NOT NULL,
    CONSTRAINT INT_METADATA_STORE_PK PRIMARY KEY (METADATA_KEY, REGION)
);
