-- P6 outbound signed webhooks: subscriptions (https URL, subscribed events, AES-256-GCM encrypted signing
-- secret) and the delivery queue worked by the scheduled dispatcher.

CREATE TABLE webhook_subscription (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    url varchar(2048) NOT NULL,
    events text[] NOT NULL,
    -- "v1:" + base64(12-byte IV || ciphertext || 16-byte GCM tag) under EDUCORE_ENCRYPTION_KEY.
    secret_encrypted varchar(512) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_by bigint,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_webhook_subscription PRIMARY KEY (id),
    CONSTRAINT ck_webhook_subscription_https CHECK (url LIKE 'https://%')
);

-- One row per (event, subscription). id is the X-EduCore-Delivery header value. payload is the exact
-- envelope that is signed and sent. next_attempt_at doubles as a lease while a dispatcher sends the row.
CREATE TABLE webhook_delivery (
    id uuid NOT NULL,
    subscription_id bigint NOT NULL,
    event varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    attempt integer DEFAULT 0 NOT NULL,
    status varchar(16) NOT NULL,
    next_attempt_at timestamp(6) with time zone,
    response_code integer,
    last_error varchar(255),
    created_at timestamp(6) with time zone NOT NULL,
    delivered_at timestamp(6) with time zone,
    CONSTRAINT pk_webhook_delivery PRIMARY KEY (id),
    CONSTRAINT fk_webhook_delivery_subscription FOREIGN KEY (subscription_id)
        REFERENCES webhook_subscription (id) ON DELETE CASCADE,
    CONSTRAINT ck_webhook_delivery_status CHECK (status IN ('PENDING', 'DELIVERED', 'FAILED'))
);

CREATE INDEX ix_webhook_delivery_due ON webhook_delivery (status, next_attempt_at);
CREATE INDEX ix_webhook_delivery_subscription ON webhook_delivery (subscription_id, created_at DESC);
