-- Restore safety of erasure (AC-09, docs/ops/BACKUP_RESTORE.md "Erasure ledger").
--
-- erasure_ledger: one row per purged account, without personal data: keyed HMAC-SHA-256 digests (key derived
-- from EDUCORE_LOGIN_PEPPER, label educore/erasure-ledger/v1) of the account id, the username and the student
-- number, plus the purge time. The purge job also appends the same line to an append-only file on a volume that
-- is not part of the database dump (EDUCORE_ERASURE_LEDGER_FILE), so a restored old dump cannot bring an erased
-- account back: post-restore.sh and the application's startup replay purge it again.
--
-- restore_replay: a restore that still needs its replay (written by scripts/backup/post-restore.sql, or by the
-- application when the ledger file holds entries the database does not know). The application completes it at
-- startup, before it serves traffic.
--
-- IF NOT EXISTS: pg_restore --clean of a dump taken before this migration leaves these tables in place while it
-- rewinds flyway_schema_history, so this migration may run again over existing tables.

CREATE TABLE IF NOT EXISTS erasure_ledger (
    account_digest varchar(64) NOT NULL,
    username_digest varchar(64) NOT NULL,
    student_number_digest varchar(64),
    purged_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT pk_erasure_ledger PRIMARY KEY (account_digest),
    CONSTRAINT ck_erasure_ledger_digests CHECK (
        account_digest ~ '^[0-9a-f]{64}$'
        AND username_digest ~ '^[0-9a-f]{64}$'
        AND (student_number_digest IS NULL OR student_number_digest ~ '^[0-9a-f]{64}$'))
);

CREATE TABLE IF NOT EXISTS restore_replay (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source varchar(32) NOT NULL,
    requested_at timestamp(6) with time zone NOT NULL,
    completed_at timestamp(6) with time zone,
    accounts_purged integer,
    accounts_to_review integer,
    CONSTRAINT pk_restore_replay PRIMARY KEY (id),
    CONSTRAINT ck_restore_replay_source CHECK (source IN ('POST_RESTORE', 'LEDGER_FILE_AHEAD'))
);

CREATE INDEX IF NOT EXISTS ix_restore_replay_pending ON restore_replay (id) WHERE completed_at IS NULL;
