server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Docker içerisindeki ayar klasörü yolu
          search-locations: file:/config-repo